<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="Originally from Los Angeles, California, I am currently pursuing a Masters degree in Financial Analysis at London Business School. Despite the stereotype that accompanies my studies, I find myself to be a &#39;people person.&#39; I thrive in group work, although I do usually prefer to work independently. As for my interests, I have experience in quite a range areas, from special needs education, beauty pageants, journalism, travel, and dance. While all are rather unrelated, they&#39;ve encouraged me to keep an open mind and to take every opportunity to learn. In addition, they&#39;ve all contributed tremendously to my abilities, such as practicing patience, managing my time, adapting quickly, and remaining organised. ">
	<meta name="author" content="Mayssa Maring">
	<meta name="generator" content="Hugo 0.75.1" />
	<title>Do men make more money than women? &middot; Portfolio Website for Mayssa Maring</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="/" class="logo"><strong>Mayssa Maring</strong> <span></span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="/">Home</a></li>
            
                <li><a href="/projects/project5">Airbnbs in Athens</a></li>
            
                <li><a href="/projects/project1">Do men earn more than women?</a></li>
            
                <li><a href="/projects/project2">Historical Yield Curves</a></li>
            
                <li><a href="/projects/project3">Trump&#39;s Approval Ratings</a></li>
            
                <li><a href="/projects/project4">Who Uses Social Media?</a></li>
            

        </ul>
        <ul class="actions vertical">
            
                <li><a href="/blogs" class="button special fit">Get Started</a></li>
            
            
                <li><a href="/" class="button fit"></a></li>
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>Do men make more money than women?</h1>
                            </header>
                            
                            


<div id="omega-group-plc--pay-discrimination" class="section level1">
<h1>Omega Group plc- Pay Discrimination</h1>
<p>At the last board meeting of Omega Group Plc., the headquarters of a large multinational company, the issue was raised that women were being discriminated in the company, in the sense that the salaries were not the same for male and female executives. A quick analysis of a sample of 50 employees (of which 24 men and 26 women) revealed that the average salary for men was about 8,700 higher than for women. This seemed like a considerable difference, so it was decided that a further analysis of the company salaries was warranted.</p>
<p>Our job has been focused on performing an analysis in order to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<div id="we-have-worked-with-the-following-data" class="section level2">
<h2>We have worked with the following data:</h2>
<pre class="r"><code>setwd(&quot;C:/Users/mayss/Documents/LBS_Term1/Data Analytics for Finance/my_website/content/projects/project1&quot;)

omega &lt;- read_csv(file=&#39;data/omega.csv&#39;)
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, ...
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, ...
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24...</code></pre>
</div>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship Salary - Gender ?</h2>
<p>Calculate summary statistics on salary by gender. Also, create and print a dataframe where, for each gender, you show the mean, SD, sample size, the t-critical, the SE, the margin of error, and the low/high endpoints of a 95% condifence interval</p>
<pre class="r"><code># Summary Statistics of salary by gender:
mosaic::favstats (salary ~ gender, data=omega)</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># We now calculate the t-critical value, the standard error, the margin of error and the low/high endpoints of a 95% condifence interval:

omegastats&lt;-omega%&gt;%
select(salary,gender)%&gt;%
  group_by(gender)%&gt;%
  summarise(
    mean=mean(salary), # mean calculation
    SD=sd(salary), # standard deviation calculation
    SampleSize=n(), # sample size counting
    t_crit=qt(0.975,SampleSize-1), # t-critical value calculation
    SE=SD/sqrt(SampleSize), # standard error calculation
    MarginError=t_crit*SE, # margin error calculation
    Lowend=mean-MarginError, # low end point of the confidence interval
    Highend=mean+MarginError) # high end point of the confidence interval

omegastats</code></pre>
<pre><code>## # A tibble: 2 x 9
##   gender   mean    SD SampleSize t_crit    SE MarginError Lowend Highend
##   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;      &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 female 64543. 7567.         26   2.06 1484.       3056. 61486.  67599.
## 2 male   73239. 7463.         24   2.07 1523.       3151. 70088.  76390.</code></pre>
<blockquote>
<p>What can you conclude from your analysis?</p>
</blockquote>
<p>It can be stated that there is a significant difference since the confidence intervals do not overlap. The high end of female salaries is 67,599 whereas the low end for male salaries is 70,088.</p>
<p>We will now use hypothesis testing analysis:</p>
<pre class="r"><code># hypothesis testing using t.test() 

t.test(salary ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salary by gender
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean in group female   mean in group male 
##                64543                73239</code></pre>
<pre class="r"><code># hypothesis testing using infer package

initialize_null &lt;-omega%&gt;%
specify(salary ~ gender)%&gt;%
calculate(stat=&quot;diff in means&quot;,order=c(&quot;female&quot;,&quot;male&quot;)) 

#Simulate the hypothesis test

salaries_null&lt;-omega%&gt;%
  specify(salary ~ gender)%&gt;%
  hypothesize(null=&quot;independence&quot;)%&gt;%
  generate(reps=10000,type=&quot;permute&quot;)%&gt;%
  calculate(stat=&quot;diff in means&quot;,order=c(&quot;female&quot;,&quot;male&quot;))

#Plotting the distribution and obtaining p value

salaries_null %&gt;% visualize() +
  shade_p_value(obs_stat = initialize_null, direction = &quot;two-sided&quot;, color=&quot;black&quot;)+
  labs(x=&quot;Difference between mean salaries&quot;,y=&quot;# of repetitions&quot;,title=&quot;Any significant difference between men and women&#39;s salaries?&quot;,subtitle=&quot;Null hypothesis distribution and p-value&quot;)+theme_economist()</code></pre>
<p><img src="//projects/project1/index_files/figure-html/hypothesis_testing-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Getting the p value

salaries_null %&gt;% get_p_value(obs_stat = initialize_null, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1  0.0002</code></pre>
<blockquote>
<p>What can you conclude from your analysis?</p>
</blockquote>
<p>It can be concluded that we can reject the null hypothesis with a 95% confidence interval. We can observe the p-value being really far from 0, which would mean that there are no significant difference among the means. For this reason, we can affirm that in statistical terms there is certainly a significant difference between male and female salaries. Is the reason discrimination? We can’t say, a further analysis must be performed in order to find out. We will now check the relationship with experience and gender in order to go deeper in our analysis.</p>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender?</h2>
<pre class="r"><code># Summary Statistics of salary by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<pre class="r"><code>omegastats2&lt;-omega%&gt;%
select(experience,gender)%&gt;%
  group_by(gender)%&gt;%
  summarise(
    mean=mean(experience), #mean calculation
    SD=sd(experience), # standard deviation calculation
    SampleSize=n(), # sample size counting
    t_crit=qt(0.975,SampleSize-1), # t critical calculation
    SE=SD/sqrt(SampleSize), # standard error calculation
  MarginError=t_crit*SE, # margin error calculation
  LowEnd=mean-MarginError, # low end of the confidence interval
  HighEnd=mean+MarginError) # high end of the confidence interval

omegastats2</code></pre>
<pre><code>## # A tibble: 2 x 9
##   gender  mean    SD SampleSize t_crit    SE MarginError LowEnd HighEnd
##   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 female  7.38  8.51         26   2.06  1.67        3.44   3.95    10.8
## 2 male   21.1  10.9          24   2.07  2.23        4.61  16.5     25.7</code></pre>
<p>Based on this evidence, can you conclude that there is a significant difference between the experience of the male and female executives?</p>
<p>Due to the fact that the confidence intervals do not overlap (10.2 high end for females and 17.31 low end for males) we can state that there is a significant difference in experience. This situation might also explain the difference in salaries that we have seen in our previous analysis, but we have to perform additional analysis in order to reach a proper conclusion.</p>
<p>We now perform the same analysis with hypothesis testing:</p>
<pre class="r"><code># Hypothesis testing using t.test() 
t.test(experience ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  experience by gender
## t = -5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -19.35  -8.13
## sample estimates:
## mean in group female   mean in group male 
##                 7.38                21.12</code></pre>
<pre class="r"><code># Hypothesis testing using infer package

initialize_null &lt;- omega %&gt;%
specify(experience ~ gender)%&gt;%
calculate(stat=&quot;diff in means&quot;,order=c(&quot;female&quot;,&quot;male&quot;)) 

#Simulate hypothesis testing

experience_null &lt;- omega %&gt;%
  specify(experience ~ gender) %&gt;%
  hypothesize(null=&quot;independence&quot;) %&gt;%
  generate(reps=1000,type=&quot;permute&quot;) %&gt;%
  calculate(stat=&quot;diff in means&quot;,order=c(&quot;male&quot;,&quot;female&quot;))

#Plotting the distribution and getting p value

experience_null %&gt;% visualize() +
  shade_p_value(obs_stat = initialize_null, direction = &quot;two-sided&quot;, color =&quot;black&quot;)+
    labs(x=&quot;Difference between mean experience in genders&quot;,y=&quot;# of repetitions&quot;,title=&quot;any significant difference between men and women&#39;s experience?&quot;,subtitle=&quot;Null hypothesis distribution and p-value&quot;)+theme_economist()</code></pre>
<p><img src="//projects/project1/index_files/figure-html/unnamed-chunk-1-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Obtaining the p value

experience_null %&gt;% get_p_value(obs_stat = initialize_null, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>We get the same conclusions as in the analysis above, further analysis is required before reaching a final conclusion.</p>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience ?</h2>
<p>We draw a scatterplot to visually inspect the data:</p>
<pre class="r"><code>omega %&gt;% 
ggplot(aes(x=experience,y=salary)) + theme_economist() + geom_point() + geom_line() + labs(title=&quot;Experience vs salary relationship&quot;,x=&quot;Years of Experience&quot;,y=&quot;Salary $&quot;)</code></pre>
<p><img src="//projects/project1/index_files/figure-html/salary_exp_scatter-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>You can use <code>GGally:ggpairs()</code> to create a scatterplot and correlation matrix. Essentially, we change the order our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the dataframe to <code>ggpairs()</code> with <code>aes</code> arguments to colour by <code>gender</code> and make ths plots somewhat transparent (<code>alpha  = 0.3</code>).</p>
<pre class="r"><code>omega %&gt;% 
  select(gender, experience, salary) %&gt;% #order variables they will appear in ggpairs()
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="//projects/project1/index_files/figure-html/ggpairs-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Look at the salary vs experience scatterplot. What can you infer from this plot?</p>
</blockquote>
<p>By observing the scatterplot it can be stated that there is a positive relationship between salary and experience. Furthermore, most of the male employees have at least 5 years of experience while most female employees have less than 5 years of experience. Of those female employees that have experience between 5 and 30 years, a positive relationship between the two variables can also be observed. For this reason, we can conclude that the difference in salaries between men and female employees is due to experience and not due to discrimination.</p>
</div>
</div>

                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
                <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="icons">
                
                    <li><a href="https://www.github.com/mayssa537" class="icon alt fa-github" target="_blank"><span class="label">GitHub</span></a></li>
                
                    <li><a href="https://www.linkedin.com/in/mayssa-maring" class="icon alt fa-linkedin" target="_blank"><span class="label">LinkedIn</span></a></li>
                
            </ul>
            <ul class="copyright">
                <li>&copy; Company Name</li>
                
                <li>Design:  <a href="https://www.html5up.net">HTML5 UP</a></li>
                
            </ul>
        </div>
    </footer>

            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery.scrolly.min.js"></script>
    <script src="/js/jquery.scrollex.min.js"></script>
    <script src="/js/skel.min.js"></script>
    <script src="/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="/js/main.js"></script>

    

    

    </body>
</html>
